### ISSUE TITLE
Create instructions for assigning data without overwriting the Value as a whole

### ISSUE THREAD

**Issue by Redempt** [FenderLang/Freight#25]
Should be done after the move instructions are unified

**Comment by FuzzyNovaGoblin** [comment]
what do you mean by not overwriting the value?

**Comment by Redempt** [comment]
Mutate the internal state of the value (reference) rather than making a new one entirely

**Comment by FuzzyNovaGoblin** [comment]
that is a fender construct tho. Freight doesn't know that the values are references.

**Comment by Redempt** [comment]
There should be an `assign` method on the Value trait

**Comment by FuzzyNovaGoblin** [comment]
there is not. I was thinking that this should be handled by the implementation and that is how it would be done. Ill add a stub to the `Value` trait as well
